layout: {qmk_info_json: info.json}
layers:

  alpha:
  - [{s: "Shift", t: "tap", h: "NUM", type: ghost}]
  - [{t: "W", $$mdi:arrow-left$$},  {t: F}, {t: M}, {t: P}, {t: V}, {t: /, s: '|'}, {t: ., s: ':'},       {t: J},       {t: '''', s: '"'}, {t: Z}]
  - [{t: R, h: 'fn'},  {t: S, h: $$mdi:apple-keyboard-control$$}, {t: N, h: $$mdi:apple-keyboard-option$$}, {t: T, h: $$mdi:apple-keyboard-command$$}, {t: B, h: $$mdi:apple-keyboard-shift$$}, {t: ', ;', h: $$mdi:apple-keyboard-shift$$}, {t: "A", h: $$mdi:apple-keyboard-command$$}, {t: E, h: $$mdi:apple-keyboard-option$$},       {t: I, h: $$mdi:apple-keyboard-control$$},    {t: H, h: 'fn'}]
  - [{t: X},  {t: C}, {t: L}, {t: D}, {t: G}, {t: '-', s: _}, {t: "U"}, {t: "O"}, {t: Y},    {t: K}]
  - - {t: $$tabler:repeat$$,     s: '', h: 'mo_numbers', type: held}
    - {t: '⌫ Word',                   s: '', h: 'mo_symbols'}
    - {t: ⌴,  s: '',   h: "mo_CHORD"}
    - {t: $$tabler:arrow-back$$, s: '',     h: "mo_CMD",     type: held}
  symbols:
  - [{s: "Shift or hold", t: "tap", h: "", type: ghost}]
  - [{s: "", t: $$mdi:arrow-left$$, h: ""},   {s: "", t: "$$mdi:arrow-down$$", h: ""},   {s: "", t: '$$mdi:arrow-up$$', h: ""},   {s: "", t: "$$mdi:arrow-right$$", h: ""}, {s: "", t: "^", h: ""},  {s: "", t: "\\", h: ""}, {s: "", t: "!", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "`", h: ""}, {s: "", t: "", h: ""}]
  - [{s: "}", t: "{", h: ""}, {s: "]", t: "[", h: ""}, {s: ")", t: "(", h: ""}, {s: ">", t: "<", h: ""}, {s: "", t: "⌦", h: ""}, {s: "", t: "?", h: $$mdi:apple-keyboard-shift$$},  {s: "", t: "@", h: $$mdi:apple-keyboard-command$$}, {s: "", t: "=", h: $$mdi:apple-keyboard-option$$}, {s: "", t: "&", h: $$mdi:apple-keyboard-control$$}, {s: "", t: "#", h: 'fn'}]
  - [{s: "", t: "", h: ""},   {s: "", t: "", h: ""},   {s: "", t: "~", h: ""},  {s: "", t: "$", h: ""},  {s: "", t: "INS", h: ""},   {s: "", t: "-", h: ""},  {s: "", t: "€", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "", h: ""},  {s: "", t: "", h: ""}]
  - - {t: 'mo_FUN',              s: '', h: 'mo_numbers', type: trans}
    - {t: '⌫ Word',                   s: '', h: 'mo_symbols', type: held}
    - {t: '⌴',              s: '',   h: "mo_CHORD",   type: trans}
    - {t: $$tabler:arrow-back$$, s: '',     h: "mo_CMD",     type: trans}
  numbers:
  - [{s: "Shift", t: "normal tap", h: "", type: ghost}]
  - [{s: '/', t: '*'}, '9', '8', '7', ',',    '''', '!', '', '°', '∑']
  - [{s: '-', t: '+'}, '3', '2', '1', '0',    '§', '%', '≤', '≥', '#']
  - [{s: '^', t: '='}, '6', '5', '4', '.',    '_', 'µ', '±', '≈', '≠']
  - - {t: $$tabler:repeat$$,    s: '', h: 'mo_numbers', type: held}
    - {t: 'mo_FUN',             s: '', h: 'mo_symbols', type: trans}
    - {t: ⌴, s: '',   h: "mo_CHORD",   type: trans}
    - {t: 'to_ALP',             s: '',     h: "mo_CMD",     type: trans}
  commands:
  - [{s: "Shift", t: "tap", h: "", type: ghost}]
  - [{t: "find all"},    {t: "find"},                {t: "redo"},               {t: "undo"},                {t: "switch win"},    $$mdi:volume-minus$$,  $$mdi:volume-mute$$,   $$mdi:volume-plus$$, $$mdi:lightbulb-on-70$$, $$mdi:lightbulb-on-40$$]
  - [{t: "select all", h: 'fn'},  {t: $$mdi:content-cut$$, h: $$mdi:apple-keyboard-control$$},   {t: $$mdi:content-copy$$, h: $$mdi:apple-keyboard-option$$}, {t: $$mdi:content-paste$$, h: $$mdi:apple-keyboard-command$$}, {t: "paste hist", h: $$mdi:apple-keyboard-shift$$},    {t: 'desktop left', h: $$mdi:apple-keyboard-shift$$},  {t: 'win left', h: $$mdi:apple-keyboard-command$$},       {t: 'win middle', h: $$mdi:apple-keyboard-option$$},   {t: 'win right', h: $$mdi:apple-keyboard-control$$},        {t: 'desktop right', h: 'fn'}]
  - [{t: "find prev"},   'find next',                 'Enter',                       {t: $$mdi:keyboard-tab$$},  'switch app',              $$mdi:keyboard-esc$$, $$mdi:skip-previous$$, $$mdi:play-pause$$,  $$mdi:skip-next$$,         {t: ''}]
  - - {t: to_Alpha,              s: '',            h: ''}
    - {t: '⌫ Word',                   s: '', h: 'mo_symbols', type: trans}
    - {t: ⌴,  s: '',   h: "mo_CHORD",   type: trans}
    - {t: $$tabler:arrow-back$$, s: '',     h: "mo_CMD",     type: held}
  functions:
  - [{s: "double tap", t: "normal tap", h: "", type: ghost}]
  - [F5,  F4,  F3,  F2,  F1,    'BT_1', 'BT_2', 'BT_3', 'BT_4', 'BT_5']
  - [F10, F9,  F8,  F7,  F6,    '', F16, F17, F18, F19]
  - [F15, F14, F13, F12, F11,   'BT_CLR', 'OUT_BT', 'OUT_USB', '', '']
  - - {t: 'mo_FUN', type: held}
    - {t: 'mo_FUN', type: held}
    - {t: ⌴,  s: '', h: "mo_CHORD", type: trans}
    - {t: $$tabler:arrow-back$$, s: '',   h: "mo_CMD",   type: trans}

combos:
# lock keys
  - {p: [15, 17], k: $$mdi:sleep$$, l: [functions]}
  - {p: [14, 18], k: $$mdi:lock$$, l: [functions], a: bottom, offset: 0.15}
  - {p: [13, 19], k: $$mdi:keyboard-off$$, l: [functions], a: bottom, offset: 0.75}

# Special Alphas
  - {p: [1, 2], k: 'Qu', l: [alpha]}
  - {p: [17, 18], k: {t: 'ä', s: 'Ä'}, l: [alpha], slide: -0.3}
  - {p: [28, 18], k: {t: 'ö', s: 'Ü'}, l: [alpha], slide: 0.75, a: right, offset: -0.15}
  - {p: [27, 18], k: {t: 'ü', s: 'Ü'}, l: [alpha], slide: -0.75, a: right, offset: -1.1}
  - {p: [12, 18], k: 'ß', l: [alpha], slide: -0.93}

  - {p: [15, 16], k: 'CapsW', l: [alpha, symbols, numbers]}
  - {p: [32, 33], k: '$$tabler:backspace$$', l: [alpha, symbols, numbers, commands], a: top}

  - {p: [31, 33], k: 'Shift (CRD)', l: [alpha], a: bottom, slide: 1, offset: 1}

  # Layer switching
    # to Alp is not a chord, but a key on the COM layer
  - {p: [31, 34], k: 'to Alp', l: [alpha], a: bottom, offset: 0.5, type: held}
  - {p: [31, 34], k: 'to Alp', l: [symbols, numbers, commands], a: bottom, offset: 0.5}
  - {p: [31, 32], k: 'mo FUN', l: [], a: bottom, offset: 0.5}
  - {p: [31, 32], k: 'mo FUN', l: [functions], a: bottom, offset: 0.5, type: held}
  - {p: [29, 30], k: 'mo DAN', l: [functions]}

