layout: {qmk_info_json: info.json}
layers:
  hands_down_neu:
  - [ {s: "2x tap", t: "tap", h: "with <REP> held"} ]
  - [ {s: W, t: "w", h: "find all"},    {t: "f", s: F, h: "find"},                         {t: "m", s: M, h: "redo"},                        {t: p", s: P, h: "undo"},                          {t: "v", s: V, h: "switch app"},         {t: /, s: '|'},                          {t: ., s: ':'},                                          {t: "j", s: J},                                   {t: '''', s: '"'},                                 {t: "z", s: Z}]
  - [ {t: "r", s: R, h: "find prev"},   {t: "s", s: S, h: $$mdi:apple-keyboard-control$$}, {t: "n", s: N, h: $$mdi:apple-keyboard-option$$}, {t: "t", s: T, h: $$mdi:apple-keyboard-command$$}, {t: "b", s: B, h: $$mdi:keyboard-tab$$}, {t: ',', s: ;, h: $$mdi:keyboard-esc$$}, {t: "a", s: "A/ä/Ä", h: $$mdi:apple-keyboard-command$$}, {t: "e", s: E, h: $$mdi:apple-keyboard-option$$}, {t: "i", s: I, h: $$mdi:apple-keyboard-control$$}, {t: "h", s: H}]
  - [ {t: "x", s: X, h: "select all"},  {t: "c", s: C, h: $$mdi:content-cut$$},            {t: "l", s: L, h: $$mdi:content-copy$$},          {t: "d", s: D, h: $$mdi:content-paste$$},          {t: "v", s: V, h: "switch win"},         {t: '-', s: _},                          {t: "u", s: "U/ü/Ü"},                                    {t: "o", s: "O/ö/Ö"},                             {t: "y", s: Y},                                    {t: "k", s: K}]
  - - LSHFT
    - {t: $$tabler:repeat$$, s: 'CapsWord', h: "▽CMD", type: held}
    - {t: ⌴, s: $$tabler:backspace$$, h: '⌫ Word'}
    - {t: ▽ALP, s: number}
  symbols:
  - [ {s: "", t: "tap", h: "with <?> held"} ]
  - [ {s: "", t: "]", h: ""},  {s: "", t: "}", h: ""},  {s: "", t: ")", h: ""},  {s: "", t: ">", h: ""},  {s: "", t: "^", h: ""},   {s: "", t: "\\", h: ""}, {s: "", t: "!", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "`", h: ""}, {s: "", t: "", h: ""}]
  - [ {s: "]", t: "[", h: ""}, {s: "}", t: "{", h: ""}, {s: ")", t: "(", h: ""}, {s: ">", t: "<", h: ""}, {s: "", t: "INS", h: ""}, {s: "", t: "?", h: ""},  {s: "", t: "&", h: ""}, {s: "", t: "€", h: ""}, {s: "", t: "@", h: ""}, {s: "", t: "#", h: ""}]
  - [ {s: "", t: "", h: ""},   {s: "", t: "", h: ""},   {s: "", t: "~", h: ""},  {s: "", t: "$", h: ""},  {s: "", t: "⌦", h: ""},   {s: "", t: "-", h: ""},  {s: "", t: "=", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "", h: ""},  {s: "", t: "", h: ""}]
  - - LSHFT
    - {t: $$tabler:repeat$$, s: 'CapsWord', h: ""}
    - {t: ⌴, s: $$tabler:backspace$$, h: '⌫ Word'}
    - {t: ▽ALP, s: number}
  numbers:
  - [ {s: "double tap", t: "normal tap", h: "with REP held"} ]
  - [BSPC, '4', '5', '6', '', '', '|', '-', /, '']
  - [., '1', '2', '3', '', '', '''', _, '=', fun]
  - ['~', '7', '8', '9', '', '', +, '?', '!', '']
  - - '0'
    - SPACE
    - RET
    - {t: ▽, type: trans}
  nav:
  - [ {s: "double tap", t: "normal tap", h: "with REP held"} ]
  - ['', '', '', '', '', '', '', '', '', '']
  - - ''
    - ''
    - ''
    - ''
    - ''
    - LEFT
    - DOWN
    - UP
    - RIGHT
    - {t: ▽, type: trans}
  - ['', '', '', '', '', HOME, PG DN, PG UP, END, '']
  - - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  fun:
  - [ {s: "double tap", t: "normal tap", h: "with REP held"} ]
  - ['', F4, F5, F6, F10, '', '', '', '', '']
  - - CAPS
    - F1
    - F2
    - F3
    - F11
    - {t: BT, h: '2'}
    - MUTE
    - VOL DN
    - VOL UP
    - {type: held}
  - - lock
    - F7
    - F8
    - F9
    - F12
    - {t: BT, h: '0'}
    - {t: BT, h: '1'}
    - BRI DN
    - BRI UP
    - {t: ▽, type: trans}
  - - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ''
  danger:
  - [ {s: "double tap", t: "normal tap", h: "with REP held"} ]
  - ['', '', '', '', '', BT CLR, OUT BLE, OUT USB, '&sys_reset', '']
  - ['', '', '', '', '', '', '', '', '', '&bootloader']
  - - {t: ▽, type: trans}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: ▽, type: trans}
  - ['', '', '', '']
  lock:
  - [ {s: "double tap", t: "normal tap", h: "with REP held"} ]
  - ['', '', '', '', '', '', '', '', '', '']
  - - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {type: held}
  - - {type: held}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  - ['', '', '', '']
combos:
# Special Alphas
  - {p: [1, 2], k: 'Qu', l: [hands_down_neu]}
  # Layer switching
#    L0: normal -> thumb right outside
#    CapsWord -> thumb left outside & thumb right outside
#    L1: Commands: REP hold with combos -> thumb left inside
#    L2: SYM one-shot -> both left thumbs
  - {p: [31, 32], k: 'SYM (1sht)', l: [hands_down_neu], type: held, a: bottom, offset: 0.25}
#    L3: Num hold -> both right thumbs
  - {p: [33, 34], k: 'NUM (hold)', l: [hands_down_neu], type: held, a: bottom, offset: 0.25}
#    L4: Func one-shot -> both right thumbs & thumb left inner
#    L5: Settings -> both right thumbs & thumb left outer
#    
#    L?: ? -> both inner thumbs OR del word!
