layout: {qmk_keyboard: ferris/sweep}
layers:
  hands_down_neu:
  - [ W, F, M, P, V, {t: /, s: '|'}, {t: ., s: ':'}, J, {t: '''', s: '"'}, Z]
  - [ R, S, N, T, B, {t: ',', s: ;}, A, E, I, H]
  - [ X, C, L, D, G, {t: '-', s: _}, U, O, Y, K]
  - - LSHFT
    - {t: $$tabler:repeat$$, s: 'CapsWord'}
    - {t: ⌴, s: $$tabler:backspace$$}
    - {t: hands_down_neu, s: number}
  number:
  - [BSPC, '4', '5', '6', '', '', '|', '-', /, '']
  - [., '1', '2', '3', '', '', '''', _, '=', fun]
  - ['~', '7', '8', '9', '', '', +, '?', '!', '']
  - - '0'
    - SPACE
    - RET
    - {t: ▽, type: trans}
  nav:
  - ['', '', '', '', '', '', '', '', '', '']
  - - ''
    - ''
    - ''
    - ''
    - ''
    - LEFT
    - DOWN
    - UP
    - RIGHT
    - {t: ▽, type: trans}
  - ['', '', '', '', '', HOME, PG DN, PG UP, END, '']
  - - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  fun:
  - ['', F6, F5, F4, F10, '', '', '', '', '']
  - - CAPS
    - F3
    - F2
    - F1
    - F11
    - {t: BT, h: '2'}
    - MUTE
    - VOL DN
    - VOL UP
    - {type: held}
  - - lock
    - F9
    - F8
    - F7
    - F12
    - {t: BT, h: '0'}
    - {t: BT, h: '1'}
    - BRI DN
    - BRI UP
    - {t: ▽, type: trans}
  - - ''
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ''
  danger:
  - ['', '', '', '', '', BT CLR, OUT BLE, OUT USB, '&sys_reset', '']
  - ['', '', '', '', '', '', '', '', '', '&bootloader']
  - - {t: ▽, type: trans}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: ▽, type: trans}
  - ['', '', '', '']
  lock:
  - ['', '', '', '', '', '', '', '', '', '']
  - - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {type: held}
  - - {type: held}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  - ['', '', '', '']
combos:
  - {p: [31, 32], k: '⌫ Word', l: [hands_down_neu, number]}
# Special Alphas
  - {p: [0, 1], k: 'Qu', l: [hands_down_neu]}
  - {p: [16, 17], k: {t: 'ä', s: 'Ä'}, l: [hands_down_neu]}
  - {p: [27, 17], k: {t: 'ö', s: 'Ü'}, l: [hands_down_neu]}
  - {p: [26, 17], k: {t: 'ü', s: 'Ü'}, l: [hands_down_neu]}
  - {p: [11, 31], k: 'ß', l: [hands_down_neu]}
  # Layer switching
#    L0: normal -> thumb right outside
#    L1: Shift hold -> thumb left outside & thumb right outside
#    Commands: REP hold with combos -> thumb left inside
#    L2: SYM one-shot -> both left thumbs
#    L3: Num & Navi hold -> both right thumbs
#    L4: Func one-shot -> both right thumbs & thumb left inner
#    L5: Settings -> both right thumbs & thumb left outer
#    
#    L?: ? -> both inner thumbs OR del word!

# home row mods are sticky keys with combo of one key and REP key
  - {p: [31, 32], k: '⌫ Word', l: [hands_down_neu, number]}
