layout: {qmk_info_json: info.json}
layers:

# $$mdi:apple-keyboard-shift$$
# $$mdi:apple-keyboard-command$$
# $$mdi:apple-keyboard-option$$
# $$mdi:apple-keyboard-control$$
# "fn"

  alpha:
  - [{s: "Shift", t: "tap", h: "hold key", type: ghost}]
  - [{s: W, t: "w"},  {t: "f", s: F}, {t: "m", s: M}, {t: 'p', s: P}, {t: "v", s: V}, {t: /, s: '|'}, {t: ., s: ':'},       {t: "j", s: J},       {t: '''', s: '"'}, {t: "z", s: Z}]
  - [{t: "r", s: R, h: 'fn'},  {t: "s", s: S, h: $$mdi:apple-keyboard-control$$}, {t: "n", s: N, h: $$mdi:apple-keyboard-option$$}, {t: "t", s: T, h: $$mdi:apple-keyboard-command$$}, {t: "b", s: B, h: $$mdi:apple-keyboard-shift$$}, {t: ',', s: ;, h: $$mdi:apple-keyboard-shift$$}, {t: "a", s: "A/ä/Ä", h: $$mdi:apple-keyboard-command$$}, {t: "e", s: E, h: $$mdi:apple-keyboard-option$$},       {t: "i", s: I, h: $$mdi:apple-keyboard-control$$},    {t: "h", s: H, h: 'fn'}]
  - [{t: "x", s: X},  {t: "c", s: C}, {t: "l", s: L}, {t: "d", s: D}, {t: "g", s: G}, {t: '-', s: _}, {t: "u", s: "U/ü/Ü"}, {t: "o", s: "O/ö/Ö"}, {t: "y", s: Y},    {t: "k", s: K}]
  - - {t: $$tabler:repeat$$, s: 'tog_numbers', h: 'mo_numbers', type: held}
    - {t: '⌴',  s: 'tog_symbols', h: 'mo_symbols'}
    - {t: $$tabler:backspace$$,                   s: 'tog_CHORD',            h: "mo_CHORD"}
    - {t: $$tabler:arrow-back$$,     s: 'tog_CMD',            h: "mo_CMD", type: held}
  symbols:
  - [{s: "Shift", t: "tap", h: "", type: ghost}]
  - [{s: "", t: $$mdi:arrow-left$$, h: ""},   {s: "", t: "$$mdi:arrow-down$$", h: ""},   {s: "", t: '$$mdi:arrow-up$$', h: ""},   {s: "", t: "$$mdi:arrow-right$$", h: ""}, {s: "", t: "^", h: ""},  {s: "", t: "\\", h: ""}, {s: "", t: "!", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "`", h: ""}, {s: "", t: "", h: ""}]
  - [{s: "}", t: "{", h: ""}, {s: "]", t: "[", h: ""}, {s: ")", t: "(", h: ""}, {s: ">", t: "<", h: ""}, {s: "", t: "INS", h: ""}, {s: "", t: "?", h: $$mdi:apple-keyboard-shift$$},  {s: "", t: "@", h: $$mdi:apple-keyboard-command$$}, {s: "", t: "=", h: $$mdi:apple-keyboard-option$$}, {s: "", t: "&", h: $$mdi:apple-keyboard-control$$}, {s: "", t: "#", h: 'fn'}]
  - [{s: "", t: "", h: ""},   {s: "", t: "", h: ""},   {s: "", t: "~", h: ""},  {s: "", t: "$", h: ""},  {s: "", t: "⌦", h: ""},   {s: "", t: "-", h: ""},  {s: "", t: "€", h: ""}, {s: "", t: "", h: ""},  {s: "", t: "", h: ""},  {s: "", t: "", h: ""}]
  - - {t: $$tabler:repeat$$, s: 'tog_numbers', h: 'mo_numbers',       type: held}
    - {t: 'mo_FUN',  s: 'tog_symbols', h: 'mo_symbols',       type: trans}
    - {t: $$tabler:backspace$$,                   s: 'tog_CHORD',            h: "mo_CHORD",            type: trans}
    - {t: 'to_ALP',     s: 'tog_CMD',            h: "mo_CMD",  type: trans}
  numbers:
  - [{s: "Shift", t: "normal tap", h: "", type: ghost}]
  - [{s: '/', t: '*'}, '9', '8', '7', ',',    '''', '!', '', '°', '∑']
  - [{s: '-', t: '+'}, '3', '2', '1', '0',    '§', '%', '≤', '≥', '#']
  - [{s: '^', t: '='}, '6', '5', '4', '.',    '_', 'µ', '±', '≈', '≠']
  - - {t: 'mo_FUN', s: 'tog_numbers', h: 'mo_numbers',      type: trans}
    - {t: '⌴',  s: 'tog_symbols', h: 'mo_symbols',      type: held}
    - {t: '⌫ Word',                   s: 'tog_CHORD',            h: "mo_CHORD",           type: trans}
    - {t: $$tabler:arrow-back$$,     s: 'tog_CMD',            h: "mo_CMD", type: trans}
  commands:
  - [{s: "Shift", t: "tap", h: "", type: ghost}]
  - [{t: "find all"},    {t: "find"},                {t: "redo"},               {t: "undo"},                {t: "switch app"},    $$mdi:volume-minus$$,  $$mdi:volume-mute$$,   $$mdi:volume-plus$$, $$mdi:lightbulb-on-70$$, $$mdi:lightbulb-on-40$$]
  - [{t: "select all", h: 'fn'},  {t: $$mdi:content-cut$$, h: $$mdi:apple-keyboard-control$$},   {t: $$mdi:content-copy$$, h: $$mdi:apple-keyboard-option$$}, {t: $$mdi:content-paste$$, h: $$mdi:apple-keyboard-command$$}, {t: "switch win", h: $$mdi:apple-keyboard-shift$$},    {t: 'desktop left', h: $$mdi:apple-keyboard-shift$$},  {t: 'win left', h: $$mdi:apple-keyboard-command$$},       {t: 'win middle', h: $$mdi:apple-keyboard-option$$},   {t: 'win right', h: $$mdi:apple-keyboard-control$$},        {t: 'desktop right', h: 'fn'}]
  - [{t: "find prev"},   'find next',                 '',                       {t: $$mdi:keyboard-tab$$},  'Enter',              $$mdi:keyboard-esc$$, $$mdi:skip-previous$$, $$mdi:play-pause$$,  $$mdi:skip-next$$,         {t: ''}]
  - - {t: to_Alpha, s: '', h: ''}
    - {t: '⌴',  s: 'tog_symbols', h: 'mo_symbols',      type: trans}
    - {t: $$tabler:backspace$$,                   s: 'tog_CHORD',            h: "mo_CHORD",            type: trans}
    - {t: $$tabler:arrow-back$$, s: 'tog_CMD', h: "mo_CMD", type: held}
  functions:
  - [{s: "double tap", t: "normal tap", h: "", type: ghost}]
  - [F5,  F4,  F3,  F2,  F1,    'BT_1', 'BT_2', 'BT_3', 'BT_4', 'BT_5']
  - [F10, F9,  F8,  F7,  F6,    '', F16, F17, F18, F19]
  - [F15, F14, F13, F12, F11,   'BT_CLR', 'OUT_BT', 'OUT_USB', '', '']
  - - {t: 'mo_FUN', type: held}
    - {t: 'mo_FUN', type: held}
    - {t: $$tabler:backspace$$, s: 'tog_CHORD', h: "mo_CHORD", type: trans}
    - {t: $$tabler:arrow-back$$, s: 'tog_CMD', h: "mo_CMD", type: trans}
  danger:
  - [{s: "double tap", t: "normal tap", h: '', type: ghost}]
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', {type: held}, {type: held}]
  - [{type: held}, {type: held}, '', '']
  lock:
  - [{s: "double tap", t: "normal tap", h: "with REP held", type: ghost}]
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', {t: $$mdi:keyboard-off$$, type: held}, {t: $$mdi:sleep$$, type: held}, {t: $$mdi:lock$$, type: held}, {t: $$mdi:lock$$, type: held}, {t: $$mdi:sleep$$, type: held}, {t: $$mdi:keyboard-off$$, type: held}, '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '']
combos:
# danger keys
  - {p: [15, 16], k: 'sys reset', l: [danger], a: top}
  - {p: [14, 17], k: 'boot- loader', l: [danger], a: bottom}

# Special Alphas
  - {p: [1, 2], k: 'Qu', l: [alpha]}
  - {p: [15, 16, 32], k: 'CapsW', l: [alpha]}

  - {p: [32, 33], k: '⌫ Word', l: [alpha, symbols, numbers, commands], a: top}

# HRM - not as chord, but mod-morph-shift, in all layers 
#  - {p: [11, 33], k: $$mdi:apple-keyboard-shift$$, l: [alpha, symbols], a: left, slide: -1, offset: -0.05}
#  - {p: [12, 33], k: $$mdi:apple-keyboard-control$$, l: [alpha, symbols], a: left, slide: -1, offset: -0.15}
#  - {p: [13, 33], k: $$mdi:apple-keyboard-option$$, l: [alpha, symbols], a: left, slide: -1, offset: -0.15}  
#  - {p: [14, 33], k: $$mdi:apple-keyboard-command$$, l: [alpha, symbols], a: left, slide: -1, offset: -0.15}
#  - {p: [15, 33], k: "fn", l: [alpha, symbols], a: left, slide: -1, offset: -0.15}
#
#  - {p: [16, 33], k: "fn", l: [alpha, symbols, numbers], a: right, slide: 1, offset: -0.15}
#  - {p: [17, 33], k: $$mdi:apple-keyboard-command$$, l: [alpha, symbols, numbers], a: right, slide: 1, offset: -0.05}
#  - {p: [18, 33], k: $$mdi:apple-keyboard-option$$, l: [alpha, symbols, numbers], a: right, slide: 1, offset: -0.15}  
#  - {p: [19, 33], k: $$mdi:apple-keyboard-control$$, l: [alpha, symbols, numbers], a: right, slide: 1, offset: -0.15}
#  - {p: [20, 33], k: $$mdi:apple-keyboard-shift$$, l: [alpha, symbols, numbers], a: right, slide: 1, offset: -0.1}

  # Layer switching
    # to Alp is not a chord, but a key on the COM layer
  - {p: [31, 34], k: 'to Alp', l: [alpha], a: bottom, offset: 0.5, type: held}
  - {p: [31, 34], k: 'to Alp', l: [symbols, numbers, commands], a: bottom, offset: 0.5}
  - {p: [31, 32], k: 'mo FUN', l: [], a: bottom, offset: 0.5}
  - {p: [31, 32], k: 'mo FUN', l: [functions], a: bottom, offset: 0.5, type: held}
  - {p: [29, 30], k: 'mo DAN', l: [functions]}
  - {p: [29, 30], k: 'mo DAN', l: [danger], type: held}

#  - {p: [33, 34], k: 'NUM (hold)', l: [alpha], type: held, a: bottom, offset: 0.25}
#  - {p: [31, 32], k: 'SYM (1sht)', l: [alpha], type: held, a: bottom, offset: 0.25}

#    L0: normal -> thumb right outside
#    CapsWord -> thumb left outside & thumb right outside
#    L1: Commands: REP hold with combos -> thumb left inside
#    L2: SYM one-shot -> both left thumbs
#    L3: Num hold -> both right thumbs
#    L4: Func one-shot -> both right thumbs & thumb left inner
#    L5: Settings -> both right thumbs & thumb left outer
#    
#    L?: ? -> both inner thumbs OR del word!
